calculate focal of camera and distance from object
Gradient-PG/Drones pull request #6
Opened 2021-04-12 15:21 UTC by Mboshy

2021-04-12 21:22 UTC, DominikKwiatkowski requested changes
please use pre-commit hooks from tutorial and fix all coding style issues

2021-04-18 18:12 UTC, Mboshy commented
I need to investigate what is wrong. It passed all tests when I commited via git bash, but on github few failed

2021-04-18 18:57 UTC, Mboshy commented on drones/image_processing/__init__.py
> +from drones.image_processing.utils import calculate_focal, distance_to_camera
I have no idea at the moment how to solve this problem with "No newline at end of file"

2021-04-18 19:24 UTC, Mboshy commented
Does anyone know what should I fix? I see that there is an issue with __init__.py. No clue what is wrong

2021-04-18 19:46 UTC, bazylip commented
All files should end in a newline. Add newline at the end of `__init__.py`. Black should reformat it on its own, so there is a high chance your pre-commit setup is wrong. Flake8 will probably also fail, because your variable names are not PEP8 compliant.

2021-04-19 11:40 UTC, bazylip requested changes

2021-04-19 11:40 UTC, bazylip commented on drones/image_processing/utils.py
> +    except ZeroDivisionError as err:
There is no need to catch an exception just to raise it in the following line.

2021-04-19 11:40 UTC, bazylip commented on drones/image_processing/utils.py
> +    except ZeroDivisionError as err:
Same exception issue here.

2021-04-19 11:40 UTC, bazylip commented on drones/image_processing/utils.py
> +def vector_to_centre(frame_width: int, frame_height: int, obj_coordinates: tuple, centre_height_coeff: float) -> tuple:
Please use `typing.Tuple` in type hints.

2021-04-20 06:58 UTC, bazylip requested changes

2021-04-20 06:58 UTC, bazylip commented on drones/image_processing/utils.py
> +def vector_to_centre(frame_width: int, frame_height: int, obj_coordinates: Tuple, centre_height_coeff: float) -> Tuple:
Please specify tuple members' type as well. Take a look [here](https://docs.python.org/3/library/typing.html#typing.Tuple) to see more examples.

2021-04-29 11:11 UTC, DominikKwiatkowski approved these changes

2021-05-06 18:52 UTC, bazylip approved these changes

2021-05-06 18:52 UTC, merged